<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/historico_vt.php');
	include_once(__DIR__ . '/historico_vt_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('historico_vt');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'historico_vt';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`historico_vt`.`VcrId`" => "VcrId",
		"`historico_vt`.`VcrCodHis`" => "VcrCodHis",
		"`historico_vt`.`VcrDir`" => "VcrDir",
		"IF(    CHAR_LENGTH(`barrios1`.`VcrBarVer`), CONCAT_WS('',   `barrios1`.`VcrBarVer`), '') /* BARRIO: */" => "VcrIdBarVe",
		"IF(    CHAR_LENGTH(`comunas1`.`VcrCom`), CONCAT_WS('',   `comunas1`.`VcrCom`), '') /* COMUNA: */" => "VcrIdCom",
		"IF(    CHAR_LENGTH(`corregimientos1`.`VcrCorr`), CONCAT_WS('',   `corregimientos1`.`VcrCorr`), '') /* CORREGIMIENTO: */" => "VcrIdCorr",
		"`historico_vt`.`VcrLon`" => "VcrLon",
		"`historico_vt`.`VcrLat`" => "VcrLat",
		"`historico_vt`.`VcrDirNom`" => "VcrDirNom",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`historico_vt`.`VcrId`',
		2 => '`historico_vt`.`VcrCodHis`',
		3 => 3,
		4 => '`barrios1`.`VcrBarVer`',
		5 => '`comunas1`.`VcrCom`',
		6 => '`corregimientos1`.`VcrCorr`',
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`historico_vt`.`VcrId`" => "VcrId",
		"`historico_vt`.`VcrCodHis`" => "VcrCodHis",
		"`historico_vt`.`VcrDir`" => "VcrDir",
		"IF(    CHAR_LENGTH(`barrios1`.`VcrBarVer`), CONCAT_WS('',   `barrios1`.`VcrBarVer`), '') /* BARRIO: */" => "VcrIdBarVe",
		"IF(    CHAR_LENGTH(`comunas1`.`VcrCom`), CONCAT_WS('',   `comunas1`.`VcrCom`), '') /* COMUNA: */" => "VcrIdCom",
		"IF(    CHAR_LENGTH(`corregimientos1`.`VcrCorr`), CONCAT_WS('',   `corregimientos1`.`VcrCorr`), '') /* CORREGIMIENTO: */" => "VcrIdCorr",
		"`historico_vt`.`VcrLon`" => "VcrLon",
		"`historico_vt`.`VcrLat`" => "VcrLat",
		"`historico_vt`.`VcrDirNom`" => "VcrDirNom",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`historico_vt`.`VcrId`" => "ID HISTORICO ",
		"`historico_vt`.`VcrCodHis`" => "CONSECUTIVO:",
		"`historico_vt`.`VcrDir`" => "DIRECCION:",
		"IF(    CHAR_LENGTH(`barrios1`.`VcrBarVer`), CONCAT_WS('',   `barrios1`.`VcrBarVer`), '') /* BARRIO: */" => "BARRIO:",
		"IF(    CHAR_LENGTH(`comunas1`.`VcrCom`), CONCAT_WS('',   `comunas1`.`VcrCom`), '') /* COMUNA: */" => "COMUNA:",
		"IF(    CHAR_LENGTH(`corregimientos1`.`VcrCorr`), CONCAT_WS('',   `corregimientos1`.`VcrCorr`), '') /* CORREGIMIENTO: */" => "CORREGIMIENTO:",
		"`historico_vt`.`VcrLon`" => "LONGITUD:",
		"`historico_vt`.`VcrLat`" => "LATITUD:",
		"`historico_vt`.`VcrDirNom`" => "DIRECCION NOMENCLATURA",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`historico_vt`.`VcrId`" => "VcrId",
		"`historico_vt`.`VcrCodHis`" => "VcrCodHis",
		"`historico_vt`.`VcrDir`" => "VcrDir",
		"IF(    CHAR_LENGTH(`barrios1`.`VcrBarVer`), CONCAT_WS('',   `barrios1`.`VcrBarVer`), '') /* BARRIO: */" => "VcrIdBarVe",
		"IF(    CHAR_LENGTH(`comunas1`.`VcrCom`), CONCAT_WS('',   `comunas1`.`VcrCom`), '') /* COMUNA: */" => "VcrIdCom",
		"IF(    CHAR_LENGTH(`corregimientos1`.`VcrCorr`), CONCAT_WS('',   `corregimientos1`.`VcrCorr`), '') /* CORREGIMIENTO: */" => "VcrIdCorr",
		"`historico_vt`.`VcrLon`" => "VcrLon",
		"`historico_vt`.`VcrLat`" => "VcrLat",
		"`historico_vt`.`VcrDirNom`" => "VcrDirNom",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['VcrIdBarVe' => 'BARRIO:', 'VcrIdCom' => 'COMUNA:', 'VcrIdCorr' => 'CORREGIMIENTO:', ];

	$x->QueryFrom = "`historico_vt` LEFT JOIN `barrios` as barrios1 ON `barrios1`.`VcrIdBarVe`=`historico_vt`.`VcrIdBarVe` LEFT JOIN `comunas` as comunas1 ON `comunas1`.`VcrIdCom`=`historico_vt`.`VcrIdCom` LEFT JOIN `corregimientos` as corregimientos1 ON `corregimientos1`.`VcrIdCorr`=`historico_vt`.`VcrIdCorr` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'historico_vt_view.php';
	$x->TableTitle = 'Historico vt';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`historico_vt`.`VcrId`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['CONSECUTIVO:', 'DIRECCION:', 'BARRIO:', 'COMUNA:', 'CORREGIMIENTO:', 'LONGITUD:', 'LATITUD:', 'DIRECCION NOMENCLATURA', ];
	$x->ColFieldName = ['VcrCodHis', 'VcrDir', 'VcrIdBarVe', 'VcrIdCom', 'VcrIdCorr', 'VcrLon', 'VcrLat', 'VcrDirNom', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/historico_vt_templateTV.html';
	$x->SelectedTemplate = 'templates/historico_vt_templateTVS.html';
	$x->TemplateDV = 'templates/historico_vt_templateDV.html';
	$x->TemplateDVP = 'templates/historico_vt_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: historico_vt_init
	$render = true;
	if(function_exists('historico_vt_init')) {
		$args = [];
		$render = historico_vt_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: historico_vt_header
	$headerCode = '';
	if(function_exists('historico_vt_header')) {
		$args = [];
		$headerCode = historico_vt_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: historico_vt_footer
	$footerCode = '';
	if(function_exists('historico_vt_footer')) {
		$args = [];
		$footerCode = historico_vt_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
