<?php

// Data functions (insert, update, delete, form) for table historico_vt

// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function historico_vt_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('historico_vt');
	if(!$arrPerm['insert']) return false;

	$data = [
		'VcrDirNom' => Request::val('VcrDirNom', ''),
	];

	if($data['VcrId'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'ID HISTORICO ': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: historico_vt_before_insert
	if(function_exists('historico_vt_before_insert')) {
		$args = [];
		if(!historico_vt_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('historico_vt', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = $data['VcrId'];

	// automatic VcrIdBarVe if passed as filterer
	if(Request::val('filterer_VcrIdBarVe')) {
		sql("UPDATE `historico_vt` SET `VcrIdBarVe`='" . makeSafe(Request::val('filterer_VcrIdBarVe')) . "' WHERE `VcrId`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic VcrIdCom if passed as filterer
	if(Request::val('filterer_VcrIdCom')) {
		sql("UPDATE `historico_vt` SET `VcrIdCom`='" . makeSafe(Request::val('filterer_VcrIdCom')) . "' WHERE `VcrId`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic VcrIdCorr if passed as filterer
	if(Request::val('filterer_VcrIdCorr')) {
		sql("UPDATE `historico_vt` SET `VcrIdCorr`='" . makeSafe(Request::val('filterer_VcrIdCorr')) . "' WHERE `VcrId`='" . makeSafe($recID, false) . "'", $eo);
	}

	update_calc_fields('historico_vt', $recID, calculated_fields()['historico_vt']);

	// hook: historico_vt_after_insert
	if(function_exists('historico_vt_after_insert')) {
		$res = sql("SELECT * FROM `historico_vt` WHERE `VcrId`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!historico_vt_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('historico_vt', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) historico_vt_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function historico_vt_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function historico_vt_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('historico_vt', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: historico_vt_before_delete
	if(function_exists('historico_vt_before_delete')) {
		$args = [];
		if(!historico_vt_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `historico_vt` WHERE `VcrId`='{$selected_id}'", $eo);

	// hook: historico_vt_after_delete
	if(function_exists('historico_vt_after_delete')) {
		$args = [];
		historico_vt_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='historico_vt' AND `pkValue`='{$selected_id}'", $eo);
}

function historico_vt_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('historico_vt', $selected_id, 'edit')) return false;

	$data = [
		'VcrDirNom' => Request::val('VcrDirNom', ''),
	];

	if($data['VcrId'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'ID HISTORICO ': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('historico_vt', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: historico_vt_before_update
	if(function_exists('historico_vt_before_update')) {
		$args = ['old_data' => $old_data];
		if(!historico_vt_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'historico_vt', 
		backtick_keys_once($set), 
		['`VcrId`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="historico_vt_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['VcrId'];
	$newID = $data['VcrId'];

	$eo = ['silentErrors' => true];

	update_calc_fields('historico_vt', $data['selectedID'], calculated_fields()['historico_vt']);

	// hook: historico_vt_after_update
	if(function_exists('historico_vt_after_update')) {
		$res = sql("SELECT * FROM `historico_vt` WHERE `VcrId`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['VcrId'];
		$args = ['old_data' => $old_data];
		if(!historico_vt_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "', `pkValue`='{$data['VcrId']}' WHERE `tableName`='historico_vt' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);

	// if PK value changed, update $selected_id
	$selected_id = $newID;
}

function historico_vt_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('historico_vt');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_VcrIdBarVe = Request::val('filterer_VcrIdBarVe');
	$filterer_VcrIdCom = Request::val('filterer_VcrIdCom');
	$filterer_VcrIdCorr = Request::val('filterer_VcrIdCorr');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: VcrIdBarVe
	$combo_VcrIdBarVe = new DataCombo;
	// combobox: VcrIdCom
	$combo_VcrIdCom = new DataCombo;
	// combobox: VcrIdCorr
	$combo_VcrIdCorr = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='historico_vt' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='historico_vt' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `historico_vt` WHERE `VcrId`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'historico_vt_view.php', false);
		}
		$combo_VcrIdBarVe->SelectedData = $row['VcrIdBarVe'];
		$combo_VcrIdCom->SelectedData = $row['VcrIdCom'];
		$combo_VcrIdCorr->SelectedData = $row['VcrIdCorr'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_VcrIdBarVe->SelectedData = $filterer_VcrIdBarVe;
		$combo_VcrIdCom->SelectedData = $filterer_VcrIdCom;
		$combo_VcrIdCorr->SelectedData = $filterer_VcrIdCorr;
	}
	$combo_VcrIdBarVe->HTML = '<span id="VcrIdBarVe-container' . $rnd1 . '"></span><input type="hidden" name="VcrIdBarVe" id="VcrIdBarVe' . $rnd1 . '" value="' . html_attr($combo_VcrIdBarVe->SelectedData) . '">';
	$combo_VcrIdBarVe->MatchText = '<span id="VcrIdBarVe-container-readonly' . $rnd1 . '"></span><input type="hidden" name="VcrIdBarVe" id="VcrIdBarVe' . $rnd1 . '" value="' . html_attr($combo_VcrIdBarVe->SelectedData) . '">';
	$combo_VcrIdCom->HTML = '<span id="VcrIdCom-container' . $rnd1 . '"></span><input type="hidden" name="VcrIdCom" id="VcrIdCom' . $rnd1 . '" value="' . html_attr($combo_VcrIdCom->SelectedData) . '">';
	$combo_VcrIdCom->MatchText = '<span id="VcrIdCom-container-readonly' . $rnd1 . '"></span><input type="hidden" name="VcrIdCom" id="VcrIdCom' . $rnd1 . '" value="' . html_attr($combo_VcrIdCom->SelectedData) . '">';
	$combo_VcrIdCorr->HTML = '<span id="VcrIdCorr-container' . $rnd1 . '"></span><input type="hidden" name="VcrIdCorr" id="VcrIdCorr' . $rnd1 . '" value="' . html_attr($combo_VcrIdCorr->SelectedData) . '">';
	$combo_VcrIdCorr->MatchText = '<span id="VcrIdCorr-container-readonly' . $rnd1 . '"></span><input type="hidden" name="VcrIdCorr" id="VcrIdCorr' . $rnd1 . '" value="' . html_attr($combo_VcrIdCorr->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_VcrIdBarVe__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['VcrIdBarVe'] : htmlspecialchars($filterer_VcrIdBarVe, ENT_QUOTES)); ?>"};
		AppGini.current_VcrIdCom__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['VcrIdCom'] : htmlspecialchars($filterer_VcrIdCom, ENT_QUOTES)); ?>"};
		AppGini.current_VcrIdCorr__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['VcrIdCorr'] : htmlspecialchars($filterer_VcrIdCorr, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(VcrIdBarVe_reload__RAND__) == 'function') VcrIdBarVe_reload__RAND__();
				if(typeof(VcrIdCom_reload__RAND__) == 'function') VcrIdCom_reload__RAND__();
				if(typeof(VcrIdCorr_reload__RAND__) == 'function') VcrIdCorr_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function VcrIdBarVe_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#VcrIdBarVe-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_VcrIdBarVe__RAND__.value, t: 'historico_vt', f: 'VcrIdBarVe' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="VcrIdBarVe"]').val(resp.results[0].id);
							$j('[id=VcrIdBarVe-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdBarVe-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=barrios_view_parent]').hide(); } else { $j('.btn[id=barrios_view_parent]').show(); }


							if(typeof(VcrIdBarVe_update_autofills__RAND__) == 'function') VcrIdBarVe_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'historico_vt', f: 'VcrIdBarVe' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_VcrIdBarVe__RAND__.value = e.added.id;
				AppGini.current_VcrIdBarVe__RAND__.text = e.added.text;
				$j('[name="VcrIdBarVe"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=barrios_view_parent]').hide(); } else { $j('.btn[id=barrios_view_parent]').show(); }


				if(typeof(VcrIdBarVe_update_autofills__RAND__) == 'function') VcrIdBarVe_update_autofills__RAND__();
			});

			if(!$j("#VcrIdBarVe-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_VcrIdBarVe__RAND__.value, t: 'historico_vt', f: 'VcrIdBarVe' },
					success: function(resp) {
						$j('[name="VcrIdBarVe"]').val(resp.results[0].id);
						$j('[id=VcrIdBarVe-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdBarVe-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=barrios_view_parent]').hide(); } else { $j('.btn[id=barrios_view_parent]').show(); }

						if(typeof(VcrIdBarVe_update_autofills__RAND__) == 'function') VcrIdBarVe_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_VcrIdBarVe__RAND__.value, t: 'historico_vt', f: 'VcrIdBarVe' },
				success: function(resp) {
					$j('[id=VcrIdBarVe-container__RAND__], [id=VcrIdBarVe-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdBarVe-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=barrios_view_parent]').hide(); } else { $j('.btn[id=barrios_view_parent]').show(); }

					if(typeof(VcrIdBarVe_update_autofills__RAND__) == 'function') VcrIdBarVe_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function VcrIdCom_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#VcrIdCom-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_VcrIdCom__RAND__.value, t: 'historico_vt', f: 'VcrIdCom' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="VcrIdCom"]').val(resp.results[0].id);
							$j('[id=VcrIdCom-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCom-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=comunas_view_parent]').hide(); } else { $j('.btn[id=comunas_view_parent]').show(); }


							if(typeof(VcrIdCom_update_autofills__RAND__) == 'function') VcrIdCom_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'historico_vt', f: 'VcrIdCom' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_VcrIdCom__RAND__.value = e.added.id;
				AppGini.current_VcrIdCom__RAND__.text = e.added.text;
				$j('[name="VcrIdCom"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=comunas_view_parent]').hide(); } else { $j('.btn[id=comunas_view_parent]').show(); }


				if(typeof(VcrIdCom_update_autofills__RAND__) == 'function') VcrIdCom_update_autofills__RAND__();
			});

			if(!$j("#VcrIdCom-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_VcrIdCom__RAND__.value, t: 'historico_vt', f: 'VcrIdCom' },
					success: function(resp) {
						$j('[name="VcrIdCom"]').val(resp.results[0].id);
						$j('[id=VcrIdCom-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCom-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=comunas_view_parent]').hide(); } else { $j('.btn[id=comunas_view_parent]').show(); }

						if(typeof(VcrIdCom_update_autofills__RAND__) == 'function') VcrIdCom_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_VcrIdCom__RAND__.value, t: 'historico_vt', f: 'VcrIdCom' },
				success: function(resp) {
					$j('[id=VcrIdCom-container__RAND__], [id=VcrIdCom-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCom-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=comunas_view_parent]').hide(); } else { $j('.btn[id=comunas_view_parent]').show(); }

					if(typeof(VcrIdCom_update_autofills__RAND__) == 'function') VcrIdCom_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function VcrIdCorr_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#VcrIdCorr-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_VcrIdCorr__RAND__.value, t: 'historico_vt', f: 'VcrIdCorr' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="VcrIdCorr"]').val(resp.results[0].id);
							$j('[id=VcrIdCorr-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCorr-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=corregimientos_view_parent]').hide(); } else { $j('.btn[id=corregimientos_view_parent]').show(); }


							if(typeof(VcrIdCorr_update_autofills__RAND__) == 'function') VcrIdCorr_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'historico_vt', f: 'VcrIdCorr' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_VcrIdCorr__RAND__.value = e.added.id;
				AppGini.current_VcrIdCorr__RAND__.text = e.added.text;
				$j('[name="VcrIdCorr"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=corregimientos_view_parent]').hide(); } else { $j('.btn[id=corregimientos_view_parent]').show(); }


				if(typeof(VcrIdCorr_update_autofills__RAND__) == 'function') VcrIdCorr_update_autofills__RAND__();
			});

			if(!$j("#VcrIdCorr-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_VcrIdCorr__RAND__.value, t: 'historico_vt', f: 'VcrIdCorr' },
					success: function(resp) {
						$j('[name="VcrIdCorr"]').val(resp.results[0].id);
						$j('[id=VcrIdCorr-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCorr-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=corregimientos_view_parent]').hide(); } else { $j('.btn[id=corregimientos_view_parent]').show(); }

						if(typeof(VcrIdCorr_update_autofills__RAND__) == 'function') VcrIdCorr_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_VcrIdCorr__RAND__.value, t: 'historico_vt', f: 'VcrIdCorr' },
				success: function(resp) {
					$j('[id=VcrIdCorr-container__RAND__], [id=VcrIdCorr-container-readonly__RAND__]').html('<span class="match-text" id="VcrIdCorr-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=corregimientos_view_parent]').hide(); } else { $j('.btn[id=corregimientos_view_parent]').show(); }

					if(typeof(VcrIdCorr_update_autofills__RAND__) == 'function') VcrIdCorr_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/historico_vt_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/historico_vt_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Historico vt details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return historico_vt_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return historico_vt_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return historico_vt_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#VcrDirNom').replaceWith('<div class=\"form-control-static\" id=\"VcrDirNom\">' + (jQuery('#VcrDirNom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(VcrIdBarVe)%%>', $combo_VcrIdBarVe->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(VcrIdBarVe)%%>', $combo_VcrIdBarVe->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(VcrIdBarVe)%%>', urlencode($combo_VcrIdBarVe->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(VcrIdCom)%%>', $combo_VcrIdCom->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(VcrIdCom)%%>', $combo_VcrIdCom->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(VcrIdCom)%%>', urlencode($combo_VcrIdCom->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(VcrIdCorr)%%>', $combo_VcrIdCorr->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(VcrIdCorr)%%>', $combo_VcrIdCorr->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(VcrIdCorr)%%>', urlencode($combo_VcrIdCorr->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['VcrIdBarVe' => ['barrios', 'BARRIO:'], 'VcrIdCom' => ['comunas', 'COMUNA:'], 'VcrIdCorr' => ['corregimientos', 'CORREGIMIENTO:'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(VcrId)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrCodHis)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrDir)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrIdBarVe)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrIdCom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrIdCorr)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrLon)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrLat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VcrDirNom)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(VcrId)%%>', safe_html($urow['VcrId']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(VcrId)%%>', html_attr($row['VcrId']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrId)%%>', urlencode($urow['VcrId']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrCodHis)%%>', safe_html($urow['VcrCodHis']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrCodHis)%%>', urlencode($urow['VcrCodHis']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrDir)%%>', safe_html($urow['VcrDir']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrDir)%%>', urlencode($urow['VcrDir']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdBarVe)%%>', safe_html($urow['VcrIdBarVe']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdBarVe)%%>', urlencode($urow['VcrIdBarVe']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdCom)%%>', safe_html($urow['VcrIdCom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdCom)%%>', urlencode($urow['VcrIdCom']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdCorr)%%>', safe_html($urow['VcrIdCorr']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdCorr)%%>', urlencode($urow['VcrIdCorr']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrLon)%%>', safe_html($urow['VcrLon']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrLon)%%>', urlencode($urow['VcrLon']), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrLat)%%>', safe_html($urow['VcrLat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrLat)%%>', urlencode($urow['VcrLat']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(VcrDirNom)%%>', safe_html($urow['VcrDirNom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(VcrDirNom)%%>', html_attr($row['VcrDirNom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrDirNom)%%>', urlencode($urow['VcrDirNom']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(VcrId)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrId)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrCodHis)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrCodHis)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrDir)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrDir)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdBarVe)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdBarVe)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdCom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdCom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrIdCorr)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrIdCorr)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrLon)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrLon)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrLat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrLat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VcrDirNom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VcrDirNom)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');
	if(isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>')
		$templateCode.="\n<input type=hidden name=VcrIdBarVe value=\"" . html_attr($filterValue[1]) . "\">\n";
	if(isset($filterField[1]) && $filterField[1] == '5' && $filterOperator[1] == '<=>')
		$templateCode.="\n<input type=hidden name=VcrIdCom value=\"" . html_attr($filterValue[1]) . "\">\n";
	if(isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>')
		$templateCode.="\n<input type=hidden name=VcrIdCorr value=\"" . html_attr($filterValue[1]) . "\">\n";

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('historico_vt');
	if($selected_id) {
		$jdata = get_joined_record('historico_vt', $selected_id);
		if($jdata === false) $jdata = get_defaults('historico_vt');
		$rdata = $row;
	}
	$templateCode .= loadView('historico_vt-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: historico_vt_dv
	if(function_exists('historico_vt_dv')) {
		$args = [];
		historico_vt_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}